// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_CA_CERT_256_HASH[] =
    "7d0be232cb6b83ac06af0e8bebdb046ae75d79a5b16f556fbf1e3d34f5ea66e2";
constexpr char TEST_CA_CERT_1_HASH[] = "24ee33e4f57b2732c57247b6f897585f2d6adabb";
constexpr char TEST_CA_CERT_SPKI[] = "jLgu4ygHX1HUM4y9KcQHwjxpTxR5FNBi/AAEq4+K7gM=";
constexpr char TEST_CA_CERT_SERIAL[] = "3781cedbaa7194e99f70aae03b19ac5925de1aaf";
constexpr char TEST_CA_CERT_NOT_BEFORE[] = "Apr  8 17:30:40 2026 GMT";
constexpr char TEST_CA_CERT_NOT_AFTER[] = "Apr  5 17:30:40 2036 GMT";
