// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_EXPIRED_SPIFFE_SAN_CERT_256_HASH[] =
    "ef6477cfc7228329a1d3fd9e5ecd4e71487d11720df1ffb5ad4b06c73675407c";
constexpr char TEST_EXPIRED_SPIFFE_SAN_CERT_1_HASH[] = "91ba4b339bb92aeba5bbb1e02289053c6b8e6fb2";
constexpr char TEST_EXPIRED_SPIFFE_SAN_CERT_SPKI[] = "Oi0Hh8pF7VsrFa209KOY3ItgLiHfrjb8432p6f/2PQA=";
constexpr char TEST_EXPIRED_SPIFFE_SAN_CERT_SERIAL[] = "07b4ca2acc84c10dc0895a6542360af8aae403d4";
constexpr char TEST_EXPIRED_SPIFFE_SAN_CERT_NOT_BEFORE[] = "Apr  8 17:31:00 2026 GMT";
constexpr char TEST_EXPIRED_SPIFFE_SAN_CERT_NOT_AFTER[] = "Apr  7 17:31:00 2026 GMT";
