// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_EXPIRED_CERT_256_HASH[] =
    "69e6bd2f0b888e10a3a959cfeeeff78972e569e105b2d50b5163dd93e760ace7";
constexpr char TEST_EXPIRED_CERT_1_HASH[] = "188c2eabbb4390ee2cd70291538071d0d4afb5e0";
constexpr char TEST_EXPIRED_CERT_SPKI[] = "w1ZDRaqCOuIti5ds0+JMqnrNAvLwWuA4C1CBN7tXIu0=";
constexpr char TEST_EXPIRED_CERT_SERIAL[] = "119c0de515d3783dde64e758c7bda82a713f1332";
constexpr char TEST_EXPIRED_CERT_NOT_BEFORE[] = "Apr  8 17:30:56 2026 GMT";
constexpr char TEST_EXPIRED_CERT_NOT_AFTER[] = "Apr  7 17:30:56 2026 GMT";
