// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_EXPIRED_SAN_URI_CERT_256_HASH[] =
    "1fc406b74f7df778cf0004d45f2124e97638a4b0dcea3db73551e00adae364ac";
constexpr char TEST_EXPIRED_SAN_URI_CERT_1_HASH[] = "e1734c3524915fdb008c026ecf98dd6cd41ffde7";
constexpr char TEST_EXPIRED_SAN_URI_CERT_SPKI[] = "w6K0iQhD8YKmxGnfZKTZRegsiAepFpKtXDznWhShtIY=";
constexpr char TEST_EXPIRED_SAN_URI_CERT_SERIAL[] = "58c9956d0a2705f185fcf8015870c48ab8577316";
constexpr char TEST_EXPIRED_SAN_URI_CERT_NOT_BEFORE[] = "Apr  8 17:30:57 2026 GMT";
constexpr char TEST_EXPIRED_SAN_URI_CERT_NOT_AFTER[] = "Apr  7 17:30:57 2026 GMT";
