// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_EXTENSIONS_CERT_256_HASH[] =
    "2f672635509ad20e1c1a28b2620fe22fe2f5dffd32198af4837ec326c0e02478";
constexpr char TEST_EXTENSIONS_CERT_1_HASH[] = "4dd09e39b4c62203e3b9aca57c7392790dae3b2f";
constexpr char TEST_EXTENSIONS_CERT_SPKI[] = "RhiZcn1mVclFO992HbQKgFHYU3XBUkOVBSNdUARvnlU=";
constexpr char TEST_EXTENSIONS_CERT_SERIAL[] = "58e7263e9bd3351cc01ba28f23004b43ff0de121";
constexpr char TEST_EXTENSIONS_CERT_NOT_BEFORE[] = "Apr  8 17:30:51 2026 GMT";
constexpr char TEST_EXTENSIONS_CERT_NOT_AFTER[] = "Apr  5 17:30:51 2036 GMT";
