// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_FAKE_CA_CERT_256_HASH[] =
    "ce1e80443b9b7d0ec461d3872895e0e36af3008af72fd44318808ada0a2773ef";
constexpr char TEST_FAKE_CA_CERT_1_HASH[] = "64cb96229dfd17869c89d5f34f2580ec9197a7cf";
constexpr char TEST_FAKE_CA_CERT_SPKI[] = "QtwkjR4fHB8huhhmMEMOd9e2un9kxUzXDcB2mJgP10k=";
constexpr char TEST_FAKE_CA_CERT_SERIAL[] = "6e2f52358a895effdf520cbf93015369c55fd1b3";
constexpr char TEST_FAKE_CA_CERT_NOT_BEFORE[] = "Apr  8 17:30:42 2026 GMT";
constexpr char TEST_FAKE_CA_CERT_NOT_AFTER[] = "Apr  5 17:30:42 2036 GMT";
