// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_INTERMEDIATE_CA_CERT_256_HASH[] =
    "3eb5b128813af9ae65903e78c68dd83f1b5556a23990ef75393cd3ab4f9bf56c";
constexpr char TEST_INTERMEDIATE_CA_CERT_1_HASH[] = "5011ebd874eeb21aaac7711561de8e3c44bb941e";
constexpr char TEST_INTERMEDIATE_CA_CERT_SPKI[] = "vXNS8XlZHJx1+MYaZqMsKzJWNGAtmVmnTIrpV7vSptg=";
constexpr char TEST_INTERMEDIATE_CA_CERT_SERIAL[] = "6bd9ac007084d32260a565cbcb2e64a235a16efb";
constexpr char TEST_INTERMEDIATE_CA_CERT_NOT_BEFORE[] = "Apr  8 17:30:40 2026 GMT";
constexpr char TEST_INTERMEDIATE_CA_CERT_NOT_AFTER[] = "Apr  5 17:30:40 2036 GMT";
