// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_KEYUSAGE_CERT_SIGN_CERT_256_HASH[] =
    "6201e087da50ef7e63deebea17ddfe74482e635b19f04b644727a5a4df6864d1";
constexpr char TEST_KEYUSAGE_CERT_SIGN_CERT_1_HASH[] = "1ec8919838925883df1beeecdd07feb45d9c8326";
constexpr char TEST_KEYUSAGE_CERT_SIGN_CERT_SPKI[] = "Dyqv5CtIpeZIf1a5Ujjjie2/MBH00i2l1E9F2M/etY4=";
constexpr char TEST_KEYUSAGE_CERT_SIGN_CERT_SERIAL[] = "3fb367e652c9316433d5a469996c9a7c56c4808e";
constexpr char TEST_KEYUSAGE_CERT_SIGN_CERT_NOT_BEFORE[] = "Apr  8 17:30:58 2026 GMT";
constexpr char TEST_KEYUSAGE_CERT_SIGN_CERT_NOT_AFTER[] = "Apr  5 17:30:58 2036 GMT";
