// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_KEYUSAGE_CRL_SIGN_CERT_256_HASH[] =
    "ffd0f4cdad8a2cef09afd51d5ddf13ac3ae57e9c7509465479663ccfb481c0b1";
constexpr char TEST_KEYUSAGE_CRL_SIGN_CERT_1_HASH[] = "b663e7abda97d24ee1b6b66c7f4189442354b512";
constexpr char TEST_KEYUSAGE_CRL_SIGN_CERT_SPKI[] = "spnjugfOmhDnKd78epavqp0ZXP9CtRNKGQqiH9n0NkQ=";
constexpr char TEST_KEYUSAGE_CRL_SIGN_CERT_SERIAL[] = "1a6998f694e641b673a39581da7f49e6d132df46";
constexpr char TEST_KEYUSAGE_CRL_SIGN_CERT_NOT_BEFORE[] = "Apr  8 17:30:58 2026 GMT";
constexpr char TEST_KEYUSAGE_CRL_SIGN_CERT_NOT_AFTER[] = "Apr  5 17:30:58 2036 GMT";
