// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_LONG_VALIDITY_CERT_256_HASH[] =
    "16798c1b47eef91587483bfcccaae51b6cad2262c1e9ea026a07858a9fda6cc7";
constexpr char TEST_LONG_VALIDITY_CERT_1_HASH[] = "e589ebd3db088ae7c5de33e9cf63743a96339927";
constexpr char TEST_LONG_VALIDITY_CERT_SPKI[] = "tgpVSTqueXVP4TiFvepngRN//LhAmpf6zfNe7RjJh54=";
constexpr char TEST_LONG_VALIDITY_CERT_SERIAL[] = "47a7897ed1dd0223db3893e5d3653949124b1780";
constexpr char TEST_LONG_VALIDITY_CERT_NOT_BEFORE[] = "Apr  8 17:30:56 2026 GMT";
constexpr char TEST_LONG_VALIDITY_CERT_NOT_AFTER[] = "Mar 26 17:30:56 2076 GMT";
