// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_NO_SAN_CERT_256_HASH[] =
    "6b95fac39452c66ffab769b78a194ee98962d0a0a4d15229e80e54a6d1d44de2";
constexpr char TEST_NO_SAN_CERT_1_HASH[] = "8bc15d0e1a5ce3987f3658900c98a4d9b599e9eb";
constexpr char TEST_NO_SAN_CERT_SPKI[] = "rjVNBHvJ7+FjQziBreGA2Gj4TtBKrbdiamxCJ4Nnixc=";
constexpr char TEST_NO_SAN_CERT_SERIAL[] = "7242b7c56dcbfaa7e829b2116e1de8ebbd5644ad";
constexpr char TEST_NO_SAN_CERT_NOT_BEFORE[] = "Apr  8 17:30:43 2026 GMT";
constexpr char TEST_NO_SAN_CERT_NOT_AFTER[] = "Apr  5 17:30:43 2036 GMT";
