// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_NO_SAN_CN_CERT_256_HASH[] =
    "c4a277273af7658dfa65a70c4b3650cab7361df7cbe755019e0fa4462f55efe9";
constexpr char TEST_NO_SAN_CN_CERT_1_HASH[] = "717d86f456b5380e99ae61ea5cf9ee063eb490a1";
constexpr char TEST_NO_SAN_CN_CERT_SPKI[] = "GYIwoKzy8cVgqJnucOsBGDw83dhPhFgXWBcY05aDFVY=";
constexpr char TEST_NO_SAN_CN_CERT_SERIAL[] = "18590be73f9b839e0397ef235f9a24a6328c5141";
constexpr char TEST_NO_SAN_CN_CERT_NOT_BEFORE[] = "Apr  8 17:30:43 2026 GMT";
constexpr char TEST_NO_SAN_CN_CERT_NOT_AFTER[] = "Apr  5 17:30:43 2036 GMT";
