// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_NO_SUBJECT_CERT_256_HASH[] =
    "9d843e4b74fa75fbb9d4a757fca4a410562a97cb058f8fa9040b909a4e7a361b";
constexpr char TEST_NO_SUBJECT_CERT_1_HASH[] = "10fa6b5d9b7fe367dc479f2f53b4f3f3ae50399d";
constexpr char TEST_NO_SUBJECT_CERT_SPKI[] = "jrRpnLBn4ZRpepaOeLRvt4HbS3Lwd/wyRas7Z9xUoqU=";
constexpr char TEST_NO_SUBJECT_CERT_SERIAL[] = "54031aa4aea9d7f44bc66e9db0dca55a9ea4d103";
constexpr char TEST_NO_SUBJECT_CERT_NOT_BEFORE[] = "Apr  8 17:30:57 2026 GMT";
constexpr char TEST_NO_SUBJECT_CERT_NOT_AFTER[] = "Apr  5 17:30:57 2036 GMT";
