// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_NON_SPIFFE_SAN_CERT_256_HASH[] =
    "04c58fe7369c697809623ec865c365c92a1117fd5f1b539a437d8ed6f65761d1";
constexpr char TEST_NON_SPIFFE_SAN_CERT_1_HASH[] = "13e88e9fa1943a16f207b544ac70758d707b2b29";
constexpr char TEST_NON_SPIFFE_SAN_CERT_SPKI[] = "mtlcEAb/ws+HKXc2/JOzIQiZ0Otp1l58pdlG9dg6JlE=";
constexpr char TEST_NON_SPIFFE_SAN_CERT_SERIAL[] = "051b04333801df2a3613a9f3a010a48e67cc1438";
constexpr char TEST_NON_SPIFFE_SAN_CERT_NOT_BEFORE[] = "Apr  8 17:30:59 2026 GMT";
constexpr char TEST_NON_SPIFFE_SAN_CERT_NOT_AFTER[] = "Apr  5 17:30:59 2036 GMT";
