// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SAN_DNS_RSA_2_CERT_256_HASH[] =
    "3607ac79cb78c3a0a467a7329aa6239c3f70ca10fdaaa1e603509839d96df1b8";
constexpr char TEST_SAN_DNS_RSA_2_CERT_1_HASH[] = "3a88d19368f800a808f75524727edf6cff7f7cce";
constexpr char TEST_SAN_DNS_RSA_2_CERT_SPKI[] = "iZ4dXXKebhE6AJFBJg4WdUFhmedfccJT/YFY8qz0ThU=";
constexpr char TEST_SAN_DNS_RSA_2_CERT_SERIAL[] = "094090c139d33b733b21bf67e9d803443231a632";
constexpr char TEST_SAN_DNS_RSA_2_CERT_NOT_BEFORE[] = "Apr  8 17:30:48 2026 GMT";
constexpr char TEST_SAN_DNS_RSA_2_CERT_NOT_AFTER[] = "Apr  5 17:30:48 2036 GMT";
