// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SAN_IP_CERT_256_HASH[] =
    "9c113706b19b67c35bd1d7e6b2faffc98a9702d9d4bed399583c1c5d8832cef0";
constexpr char TEST_SAN_IP_CERT_1_HASH[] = "402745b4616c9906a479c7d0790b6b4f85ed9688";
constexpr char TEST_SAN_IP_CERT_SPKI[] = "nejnctcMRe6hGdIGP4lVv/nGmqBMzrAnSpCJ77Q9g38=";
constexpr char TEST_SAN_IP_CERT_SERIAL[] = "5f4a5a6b8be55bf62c48e224f778ade028f51922";
constexpr char TEST_SAN_IP_CERT_NOT_BEFORE[] = "Apr  8 17:30:49 2026 GMT";
constexpr char TEST_SAN_IP_CERT_NOT_AFTER[] = "Apr  5 17:30:49 2036 GMT";
