// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SAN_DNS_RSA_1_CERT_256_HASH[] =
    "e858c91a045b5f44d4f602fb683ca6cadca40007ce4945f948fc3498b71a2af5";
constexpr char TEST_SAN_DNS_RSA_1_CERT_1_HASH[] = "a0e5005007f1d686fdfe50ca33ddd27a9c19923a";
constexpr char TEST_SAN_DNS_RSA_1_CERT_SPKI[] = "cDi/6lo04d7yHhOY3DjYqFeiugyC5FbnDkSubmeWUQQ=";
constexpr char TEST_SAN_DNS_RSA_1_CERT_SERIAL[] = "218874cfa4aa611a0a68ef6ba2840274aa85a02a";
constexpr char TEST_SAN_DNS_RSA_1_CERT_NOT_BEFORE[] = "Apr  8 17:30:47 2026 GMT";
constexpr char TEST_SAN_DNS_RSA_1_CERT_NOT_AFTER[] = "Apr  5 17:30:47 2036 GMT";
