// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SAN_URI_CERT_256_HASH[] =
    "c6811245fd06ff36aa20558563446ca39fbac04daac33c30f1542c41babf5fdb";
constexpr char TEST_SAN_URI_CERT_1_HASH[] = "fdf81ba2a28f44c1097ea53342af9abf35d7ba00";
constexpr char TEST_SAN_URI_CERT_SPKI[] = "HI8dsCaxmLbRfgFm9Cx9rTHm2+jNzee+z/61eiLbqrw=";
constexpr char TEST_SAN_URI_CERT_SERIAL[] = "381d6e4754a782275a76f1a13500c645cd5d6cdc";
constexpr char TEST_SAN_URI_CERT_NOT_BEFORE[] = "Apr  8 17:30:48 2026 GMT";
constexpr char TEST_SAN_URI_CERT_NOT_AFTER[] = "Apr  5 17:30:48 2036 GMT";
