// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SAN_DNS_ECDSA_1_CERT_256_HASH[] =
    "0c353137e9b0dedabff9f1648cd1c518921fd396540ddc43f61eb8a146bc12d7";
constexpr char TEST_SAN_DNS_ECDSA_1_CERT_1_HASH[] = "cdc91631b0cc2c23861ffb03d6a9c86182e67101";
constexpr char TEST_SAN_DNS_ECDSA_1_CERT_SPKI[] = "8STOUw5oH5OZGK6YAL3D7kbRHlydtP8vLiS8Xef/HZY=";
constexpr char TEST_SAN_DNS_ECDSA_1_CERT_SERIAL[] = "33e360b496016130747b9cdf55eabb499e33ae00";
constexpr char TEST_SAN_DNS_ECDSA_1_CERT_NOT_BEFORE[] = "Apr  8 17:30:48 2026 GMT";
constexpr char TEST_SAN_DNS_ECDSA_1_CERT_NOT_AFTER[] = "Apr  5 17:30:48 2036 GMT";
