// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SAN_DNS2_CERT_256_HASH[] =
    "9399c55efaee973ff0859943fed1131ac7f7161b70ee87fdcb68a16cdf58905e";
constexpr char TEST_SAN_DNS2_CERT_1_HASH[] = "e5bc6841a80921188f5ff219e01dcf2807f3472c";
constexpr char TEST_SAN_DNS2_CERT_SPKI[] = "8GMwFF7A0omEF/tRRfdOxFbkdHld6gtMiKryX8RpKFM=";
constexpr char TEST_SAN_DNS2_CERT_SERIAL[] = "41b6b860e5143580984915693835afca1d982540";
constexpr char TEST_SAN_DNS2_CERT_NOT_BEFORE[] = "Apr  8 17:30:45 2026 GMT";
constexpr char TEST_SAN_DNS2_CERT_NOT_AFTER[] = "Apr  5 17:30:45 2036 GMT";
