// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SAN_OTHERNAME_CERT_256_HASH[] =
    "3f58aa2740cf31b23bc6970d90f227b7184059f8c854c51451b4d8ddb1a3fe4d";
constexpr char TEST_SAN_OTHERNAME_CERT_1_HASH[] = "dac4f6ee788e1d3044f282857c801d03957532bd";
constexpr char TEST_SAN_OTHERNAME_CERT_SPKI[] = "50vw8TG0EcCETidzZlndv4ykCvhgiPmTSceWoCtKKqg=";
constexpr char TEST_SAN_OTHERNAME_CERT_SERIAL[] = "6652d0dfcd07d1dd10725bd2d2cf23ca14578676";
constexpr char TEST_SAN_OTHERNAME_CERT_NOT_BEFORE[] = "Apr  8 17:30:49 2026 GMT";
constexpr char TEST_SAN_OTHERNAME_CERT_NOT_AFTER[] = "Apr  5 17:30:49 2036 GMT";
