// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SAN_DNS_CERT_256_HASH[] =
    "3605c0741b6beb9b09f8862ab2270e274626d27569807d973d109bc1dc1db14b";
constexpr char TEST_SAN_DNS_CERT_1_HASH[] = "cab98ebd67d3c7d71a6bf17269dd2c3c9be50334";
constexpr char TEST_SAN_DNS_CERT_SPKI[] = "oKCWTllKUAwLNh5Zf8koJUwSfpCGlrsWrGm2D8XqCSI=";
constexpr char TEST_SAN_DNS_CERT_SERIAL[] = "4b053499403b92d7dde534cd31228f001a0f7c04";
constexpr char TEST_SAN_DNS_CERT_NOT_BEFORE[] = "Apr  8 17:30:43 2026 GMT";
constexpr char TEST_SAN_DNS_CERT_NOT_AFTER[] = "Apr  5 17:30:43 2036 GMT";
