// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SAN_MULTIPLE_OTHERNAME_CERT_256_HASH[] =
    "76bf42c028292fe9cfcffa769130369429a45bf0a07a59accf6c3da95c716ad7";
constexpr char TEST_SAN_MULTIPLE_OTHERNAME_CERT_1_HASH[] = "1fd674b870b2f9346ed2cbb2b2f1688dbcc8024a";
constexpr char TEST_SAN_MULTIPLE_OTHERNAME_CERT_SPKI[] = "22xgu+jPwxch9cMt05scN5PV1KPMtxZhiBq+rslSJIw=";
constexpr char TEST_SAN_MULTIPLE_OTHERNAME_CERT_SERIAL[] = "643111fbbece078d6c4c51e26a077c2c6c9c6db5";
constexpr char TEST_SAN_MULTIPLE_OTHERNAME_CERT_NOT_BEFORE[] = "Apr  8 17:30:50 2026 GMT";
constexpr char TEST_SAN_MULTIPLE_OTHERNAME_CERT_NOT_AFTER[] = "Apr  5 17:30:50 2036 GMT";
