// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SAN_MULTIPLE_DNS_CERT_256_HASH[] =
    "4a0f646370a6d0c1a16aa7dde8227b03185e7cef47903cb683d1938cb26516e5";
constexpr char TEST_SAN_MULTIPLE_DNS_CERT_1_HASH[] = "eed73dcd7d1456373736e295b87e792602b46407";
constexpr char TEST_SAN_MULTIPLE_DNS_CERT_SPKI[] = "VQR5QoZII8hNCspxnSJZjLSEPdmtkZZgfHcJ2a6rrfs=";
constexpr char TEST_SAN_MULTIPLE_DNS_CERT_SERIAL[] = "4a57f828e544ab41e3ced3b54429a1ed1185c255";
constexpr char TEST_SAN_MULTIPLE_DNS_CERT_NOT_BEFORE[] = "Apr  8 17:30:46 2026 GMT";
constexpr char TEST_SAN_MULTIPLE_DNS_CERT_NOT_AFTER[] = "Apr  5 17:30:46 2036 GMT";
