// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SAN_ONLY_DNS_CERT_256_HASH[] =
    "29275ca690e6e6bdbf36aa38e7b9e850847950e6622c784a3f039357b30fb950";
constexpr char TEST_SAN_ONLY_DNS_CERT_1_HASH[] = "ff23f67728ed25a8382794d9ea5f7bfcdb9d9524";
constexpr char TEST_SAN_ONLY_DNS_CERT_SPKI[] = "gE+vib9JAr2Dfqwz8MAqy5rBXssC5SVV9qjMJdWHDac=";
constexpr char TEST_SAN_ONLY_DNS_CERT_SERIAL[] = "039fe1bc1697115bb7a256998448e73d96ac8500";
constexpr char TEST_SAN_ONLY_DNS_CERT_NOT_BEFORE[] = "Apr  8 17:30:47 2026 GMT";
constexpr char TEST_SAN_ONLY_DNS_CERT_NOT_AFTER[] = "Apr  5 17:30:47 2036 GMT";
