// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SAN_DNS4_CERT_256_HASH[] =
    "86d34ac998673800c9407fcd3e5de2da17aa8daf0ddc95d621403c72d9834986";
constexpr char TEST_SAN_DNS4_CERT_1_HASH[] = "92347676b5f7a51fdfacce1c3b70aa09d1934fb6";
constexpr char TEST_SAN_DNS4_CERT_SPKI[] = "9iwfHll9JKfkqzkkhhbCeRHWDv4zL72kSh1qLRJTRoA=";
constexpr char TEST_SAN_DNS4_CERT_SERIAL[] = "48ca0830bbd2d5285c29bfec9e825b78ded485d5";
constexpr char TEST_SAN_DNS4_CERT_NOT_BEFORE[] = "Apr  8 17:30:46 2026 GMT";
constexpr char TEST_SAN_DNS4_CERT_NOT_AFTER[] = "Apr  5 17:30:46 2036 GMT";
