// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SAN_DNS3_CERT_256_HASH[] =
    "50180aeb4497accf53ff23d3e4750e9d2802062d17540a37741e0409ffbef084";
constexpr char TEST_SAN_DNS3_CERT_1_HASH[] = "71e57c0d3e169693bbbbde52a7b57eb77cdc408a";
constexpr char TEST_SAN_DNS3_CERT_SPKI[] = "3swr+lpW3nOVX0goG8ukc1otgHDVJoLsEmI6Doc35Us=";
constexpr char TEST_SAN_DNS3_CERT_SERIAL[] = "076dab6cb47c5e0b1bbdaea1903ff6a5cf7392d6";
constexpr char TEST_SAN_DNS3_CERT_NOT_BEFORE[] = "Apr  8 17:30:45 2026 GMT";
constexpr char TEST_SAN_DNS3_CERT_NOT_AFTER[] = "Apr  5 17:30:45 2036 GMT";
