// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SAN_WILDCARD_DNS_CERT_256_HASH[] =
    "ac0bb07b36bee36876ccd0a4098b41af2baf431d94fe2bbd454a72134b5d74c5";
constexpr char TEST_SAN_WILDCARD_DNS_CERT_1_HASH[] = "8ea40d30e7e06f085bae78c495f4d2be3d2192f5";
constexpr char TEST_SAN_WILDCARD_DNS_CERT_SPKI[] = "ptZG2aStLm7SIpiZXnDRXfsaJfWoGaTvMkGncdCI2T0=";
constexpr char TEST_SAN_WILDCARD_DNS_CERT_SERIAL[] = "76e1aa1d6be35b572b87c03428cd16e291b5ead4";
constexpr char TEST_SAN_WILDCARD_DNS_CERT_NOT_BEFORE[] = "Apr  8 17:30:46 2026 GMT";
constexpr char TEST_SAN_WILDCARD_DNS_CERT_NOT_AFTER[] = "Apr  5 17:30:46 2036 GMT";
