// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SAN_DNS_ECDSA_2_CERT_256_HASH[] =
    "7d6a88cfa991b396df9f29b845406d5372e78759d99cbb19a0edf8286aea3e34";
constexpr char TEST_SAN_DNS_ECDSA_2_CERT_1_HASH[] = "69d9a7ad00223571c90fd4f19717afadc21ec21e";
constexpr char TEST_SAN_DNS_ECDSA_2_CERT_SPKI[] = "6627Jl2xhqlSEFeQ2YaX2yCSZobz96kacUq+vVPGWkE=";
constexpr char TEST_SAN_DNS_ECDSA_2_CERT_SERIAL[] = "418ff4479b573c011093ab42157ecdf93cea02af";
constexpr char TEST_SAN_DNS_ECDSA_2_CERT_NOT_BEFORE[] = "Apr  8 17:30:48 2026 GMT";
constexpr char TEST_SAN_DNS_ECDSA_2_CERT_NOT_AFTER[] = "Apr  5 17:30:48 2036 GMT";
