// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SAN_MULTIPLE_DNS_1_CERT_256_HASH[] =
    "c6b5748eda6c1e7bfab334fe4dec0d5e4f76c96c867599c281ed816f431f4b76";
constexpr char TEST_SAN_MULTIPLE_DNS_1_CERT_1_HASH[] = "b0b6eb5516dc5dea27156dde11eb1a46b3e71583";
constexpr char TEST_SAN_MULTIPLE_DNS_1_CERT_SPKI[] = "PBxId9uMNckLYImHDjI99xpJbpo9B2junIo4Sj6Uzmg=";
constexpr char TEST_SAN_MULTIPLE_DNS_1_CERT_SERIAL[] = "7ff132a88ebfd6fd9906c757cc251f571fd020c5";
constexpr char TEST_SAN_MULTIPLE_DNS_1_CERT_NOT_BEFORE[] = "Apr  8 17:30:47 2026 GMT";
constexpr char TEST_SAN_MULTIPLE_DNS_1_CERT_NOT_AFTER[] = "Apr  5 17:30:47 2036 GMT";
