// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SELFSIGNED2_CERT_256_HASH[] =
    "251289eeb6fc9965a2155fca80cad1213ae4b386122e33f8f19ee5f1bb05f790";
constexpr char TEST_SELFSIGNED2_CERT_1_HASH[] = "fd8e53cd580df2550efb106bb13bc85f7905faec";
constexpr char TEST_SELFSIGNED2_CERT_SPKI[] = "YyWhk8UL97ViYhz3MN2tNLgZ37nJYmVwVJU8lqHKVfQ=";
constexpr char TEST_SELFSIGNED2_CERT_SERIAL[] = "2ffea900859280c8a875437688552bfce930ff62";
constexpr char TEST_SELFSIGNED2_CERT_NOT_BEFORE[] = "Apr  8 17:30:52 2026 GMT";
constexpr char TEST_SELFSIGNED2_CERT_NOT_AFTER[] = "Apr  5 17:30:52 2036 GMT";
