// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SELFSIGNED_CERT_256_HASH[] =
    "79d191b387fa82b57c4381fa457e40c73113c345970c5a0ea5a49a238f443e39";
constexpr char TEST_SELFSIGNED_CERT_1_HASH[] = "0db23b8be82613462125d32761ba9494808eafe5";
constexpr char TEST_SELFSIGNED_CERT_SPKI[] = "YyWhk8UL97ViYhz3MN2tNLgZ37nJYmVwVJU8lqHKVfQ=";
constexpr char TEST_SELFSIGNED_CERT_SERIAL[] = "0f73848dcae04afab10aa3e5660f8955cea58d4f";
constexpr char TEST_SELFSIGNED_CERT_NOT_BEFORE[] = "Apr  8 17:30:52 2026 GMT";
constexpr char TEST_SELFSIGNED_CERT_NOT_AFTER[] = "Apr  5 17:30:52 2036 GMT";
