// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SPIFFE_SAN_CERT_256_HASH[] =
    "4155824adfb9dfdf11135a17b762c78080efd6bc851097e589f001a3e6d751c5";
constexpr char TEST_SPIFFE_SAN_CERT_1_HASH[] = "85cb7918bd5074bd4d52a7ac863bd895283cd3f4";
constexpr char TEST_SPIFFE_SAN_CERT_SPKI[] = "zvu7M2NQ5POJk3cjID+9P1u45cuyGk9L2jWxBpFBJ+E=";
constexpr char TEST_SPIFFE_SAN_CERT_SERIAL[] = "350ef64fc93fe4f175b6ab749494fe3f62e899d2";
constexpr char TEST_SPIFFE_SAN_CERT_NOT_BEFORE[] = "Apr  8 17:30:59 2026 GMT";
constexpr char TEST_SPIFFE_SAN_CERT_NOT_AFTER[] = "Apr  5 17:30:59 2036 GMT";
