// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_UNITTEST_CERT_256_HASH[] =
    "7af2a844010ec3dcf0ac2dd05545fbd4074e22f272f08943d4790a9601cc1290";
constexpr char TEST_UNITTEST_CERT_1_HASH[] = "ad98c0753009f115724816c60864445c6d6abf9b";
constexpr char TEST_UNITTEST_CERT_SPKI[] = "btxqw9OREuIKpi5maqehwDvlBIv7/WSz7YKgg4OvgxA=";
constexpr char TEST_UNITTEST_CERT_SERIAL[] = "276e89fb921d64c331dfaf311894cd312ea1675f";
constexpr char TEST_UNITTEST_CERT_NOT_BEFORE[] = "Apr  8 17:30:58 2026 GMT";
constexpr char TEST_UNITTEST_CERT_NOT_AFTER[] = "Apr  5 17:30:58 2036 GMT";
